### ISSUE TITLE
Update http-proxy-agent and https-proxy-agent deps

### ISSUE THREAD

**Issue by ChALkeR** [TooTallNate/node-pac-proxy-agent#16]
Those are outdated atm and use old Buffer API, which is going to start printing runtime warnings on Node.js 10.0.

Tracking: nodejs/node#19079

**Comment by shibukawa** [comment]
And security issues exist:

- https://snyk.io/vuln/npm:http-proxy-agent:20180406
- https://snyk.io/vuln/npm:https-proxy-agent:20180402

**Comment by ChALkeR** [comment]
@shibukawa That was the primary reason for opening this issue here.

**Comment by ChALkeR** [comment]
@TooTallNate Thanks!

**Comment by shibukawa** [comment]
@TooTallNate Thank you for your quick response!
