### ISSUE TITLE
Dependency on 'get-uri@2.0.3' causes [DEP0005] DeprecationWarning: Buffer()

### ISSUE THREAD

**Issue by baerrach** [TooTallNate/node-pac-proxy-agent#21]
See https://github.com/TooTallNate/node-get-uri/issues/18

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
