### ISSUE TITLE
Fetch of an https resource failed

### ISSUE THREAD

**Issue by dogawaf** [TooTallNate/node-pac-proxy-agent#3]
Hi

I encounter a weird behavior using a PAC file, and I wonder to know if pac-proxy-agent would be the cause.

I have to request a resource on a https endpoint: `https://www.example.com/foo.png`.
But the proxy server send back a response in HTML, saying that the remote server is not available.
When I am inspecting the error message returned by the proxy, I can read that the resource that the proxy tried to fetch is at `http://www.example.com:443/foo.png`.

Is pac-proxy-agent responsible for the rewriting from https to http + port 443?

Cheers

**Comment by TooTallNate** [comment]
I think I need more complete example code to reproduce this.

**Comment by tehdeadone** [comment]
I've tried to reproduce the problem with the latest version of pac-proxy-agent and proxy-agent and I can't. It seems to work properly in resolving the https address now

**Comment by TooTallNate** [comment]
Thanks for getting back to me. Closing this issue then!

**Comment by dogawaf** [comment]
Hi. I can't test this behavior anymore because the app which use Pac proxy agent has evolved and not contact any proxy now... But, cool to read that news ;)
