### ISSUE TITLE
Netmask vulnerability

### ISSUE THREAD

**Issue by yinzara** [TooTallNate/node-pac-proxy-agent#36]
https://www.npmjs.com/advisories/1658

This library uses the "pac-resolver" package which currently has an open PR to upgrade `netmask` to 2.0.1

https://github.com/TooTallNate/node-pac-resolver/pull/25

Once this is closed and a new version released, this project will also need to update.

**Comment by juan-restrepo** [comment]
@yinzara TooTallNate/node-pac-resolver#25 was merged yesterday. It seems that this project won't need the update, since pac-resolver released a new patch version. It should get picked up automatically by pac-proxy-agent.

**Comment by TooTallNate** [comment]
@juan-restrepo Is correct, the semver range allows for the new `4.1.1` to be picked up. Please run `yarn upgrade` or equivalent.
