### ISSUE TITLE
How to read a local PAC file

### ISSUE THREAD

**Issue by yelichi** [TooTallNate/node-pac-proxy-agent#45]
Hello mate, may I know what's the format of the uri that supports reading a local PAC file ？

For example:
If I have a PAC file in the path ```C:\abc.pac```, then should I setup the uri like this ```pac+C:\abc.pac``` or something else ?

so the code will be like this:
``` javascript
let agent = new PacProxyAgent('pac+C:\abc.pac');
```

May I know is that correct ? 

Looking forward your kindly help.
Thanks.

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
