### ISSUE TITLE
'reusing previous proxy resolver' error

### ISSUE THREAD

**Issue by alexsantos** [TooTallNate/node-pac-proxy-agent#8]
I used nyc as a code coverage tool on this code and it stated that the test for
`if ('ENOTMODIFIED' == err.code) {`
was not being reached on the current tests.
On the test for 'should work over an HTTP proxy' I added before the `http.get` another `http.get` without calling done() and the test is failing with `TypeError: FindProxyForURL is not a function`. I realised that the `self._resolver` is `null` and not the cached function.

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
